# Generated by Django 4.0.10 on 2024-08-30 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_document_access_type_remove_news_access_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfile',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsfile',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
