# Generated by Django 4.0.10 on 2024-09-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employee_level_alter_employee_job_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobTittle',
            new_name='JobTitle',
        ),
    ]
