# Generated by Django 4.0.10 on 2024-09-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_jobtittle_jobtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='creation_step',
            field=models.IntegerField(choices=[(1, 'Step one'), (2, 'Step two'), (3, 'Step three'), (4, 'Step Four'), (5, 'Step Five')], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_arrangement',
            field=models.IntegerField(choices=[(1, 'WFH'), (2, 'ON_SITE'), (3, 'WFH/ON_SITE')], default=2),
        ),
    ]
