# Generated by Django 4.0.10 on 2024-09-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_employee_age_employee_creation_step_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='contact_person_incase_of_emergency',
            new_name='cpioe',
        ),
    ]
