# Generated by Django 4.0.10 on 2024-09-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_jobtitle_status_level_status_notification_notif_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pagibig_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='phil_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='sss_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='tin_no',
            field=models.IntegerField(default=0),
        ),
    ]
