# Generated by Django 4.0.10 on 2024-09-12 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_employee_pagibig_no_alter_employee_phil_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Leave and absence'), (2, 'Overtime')], default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Suspended'), (3, 'Deleted'), (4, 'Incomplete Profile'), (5, 'For Activation')], default=1),
        ),
        migrations.AlterField(
            model_name='educbackground',
            name='educ_type',
            field=models.IntegerField(choices=[(1, 'Primary Education'), (2, 'Secondary Education'), (3, 'Tertiary Education')], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='martial_status',
            field=models.IntegerField(choices=[(1, 'Single'), (2, 'Married')], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Suspended'), (3, 'Deleted'), (4, 'Incomplete Profile'), (5, 'For Activation')], default=1),
        ),
        migrations.CreateModel(
            name='EmployeeCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Leave And Absence'), (2, 'Overtime')], default=1)),
                ('term', models.IntegerField(choices=[(1, 'Month'), (2, 'Year')], default=1)),
                ('availability', models.IntegerField(choices=[(1, 'Upon Regularization')], default=1)),
                ('compensation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clientcompensation')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('term', models.IntegerField(choices=[(1, 'Month'), (2, 'Year')], default=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('benefits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clientbenefits')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
            ],
        ),
        migrations.AddField(
            model_name='clientcompensation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client'),
        ),
        migrations.AddField(
            model_name='clientbenefits',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client'),
        ),
    ]
