# Generated by Django 4.0.10 on 2024-09-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_clientbenefits_clientcompensation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.IntegerField(choices=[(1, 'Probationary'), (2, 'Project'), (3, 'Regular')], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.IntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other')], default=3),
        ),
    ]
